In [3]:
from jupyter_dash import JupyterDash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output, State
import plotly.express as px
import pandas as pd
import io

<ipython-input-3-4d150bbf7364>:2: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
<ipython-input-3-4d150bbf7364>:3: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html

In [6]:
df = pd.read_html('https://www.basketball-reference.com/leagues/NBA_stats_per_game.html#stats', header=1)[0]

df = df.dropna(subset=['ORtg'])
df = df [['Season','ORtg']]
df['Season'].to_list()

['2021-22',
 '2020-21',
 '2019-20',
 '2018-19',
 '2017-18',
 '2016-17',
 '2015-16',
 '2014-15',
 '2013-14',
 '2012-13',
 '2011-12',
 '2010-11',
 '2009-10',
 '2008-09',
 '2007-08',
 '2006-07',
 '2005-06',
 '2004-05',
 '2003-04',
 nan,
 'Season',
 '2002-03',
 '2001-02',
 '2000-01',
 '1999-00',
 '1998-99',
 '1997-98',
 '1996-97',
 '1995-96',
 '1994-95',
 '1993-94',
 '1992-93',
 '1991-92',
 '1990-91',
 '1989-90',
 '1988-89',
 '1987-88',
 '1986-87',
 '1985-86',
 '1984-85',
 '1983-84',
 nan,
 'Season',
 '1982-83',
 '1981-82',
 '1980-81',
 '1979-80',
 '1978-79',
 '1977-78',
 '1976-77',
 '1975-76',
 '1974-75',
 '1973-74',
 nan,
 'Season']

In [ ]:
df_test = pd.read_csv(io.StringIO(""" num label  color  value1  value2  value3
   1     A    red     0.4        4      40
   2     A   blue     0.2        2      20
   3     A  green     0.3        3      30
   4     A    red     0.6        6      60
   5     A   blue     0.7        7      70
   6     A  green     0.4        4      40
   7     B   blue     0.2        2      20
   8     B  green     0.4        4      40
   9     B    red     0.4        4      40
  10     B  green     0.2        2      20
  11     C    red     0.1        1      10
  12     C   blue     0.3        3      30
  13     D    red     0.8        8      80
  14     D   blue     0.4        4      40
  15     D  green     0.6        6      60
  16     D yellow     0.5        5      50"""), sep="\s+")

# Build App
app = JupyterDash(__name__)

app.layout = html.Div(
    [
        dcc.Dropdown(
            id="color",
            options=[{"label": x, "value": x} for x in df_test["color"].unique()],
            value="red",
        ),
        dcc.Dropdown(
            id="value",
            options=[{"label": x, "value": x} for x in df_test.columns[3:]],
            value="value1",
        ),
        dcc.Graph(id="graph1"),
    ]
)


@app.callback(
    Output("graph1", "figure"),
    Input("color", "value"),
    Input("value", "value"),
)
def update_graph1(color, value):
    print(color, value)
    return px.bar(df_test.loc[df_test["color"].eq(color)], y=value)


# Run app and display result inline in the notebook
app.run_server(mode="inline")

In [ ]:
df_test = pd.read_csv(io.StringIO(""" num label  color  value1  value2  value3
   1     A    red     0.4        4      40
   2     A   blue     0.2        2      20
   3     A  green     0.3        3      30
   4     A    red     0.6        6      60
   5     A   blue     0.7        7      70
   6     A  green     0.4        4      40
   7     B   blue     0.2        2      20
   8     B  green     0.4        4      40
   9     B    red     0.4        4      40
  10     B  green     0.2        2      20
  11     C    red     0.1        1      10
  12     C   blue     0.3        3      30
  13     D    red     0.8        8      80
  14     D   blue     0.4        4      40
  15     D  green     0.6        6      60
  16     D yellow     0.5        5      50"""), sep="\s+")

# Build App
app = JupyterDash(__name__)

app.layout = html.Div(
    [
        dcc.Dropdown(
            id="color",
            options=[{"label": x, "value": x} for x in df_test["color"].unique()],
            value="red",
        ),
        dcc.Dropdown(
            id="value",
            options=[{"label": x, "value": x} for x in df_test.columns[3:]],
            value="value1",
        ),
        dcc.Graph(id="graph1"),
    ]
)


@app.callback(
    Output("graph1", "figure"),
    Input("color", "value"),
    Input("value", "value"),
)
def update_graph1(color, value):
    print(color, value)
    return px.bar(df_test.loc[df_test["color"].eq(color)], y=value)


# Run app and display result inline in the notebook
app.run_server(mode="inline")